// This code is auto-generated by MenuItemNamesCreator.
namespace Helper
{
/// <summary>
/// シーン名をEnumで管理するクラス
/// </summary>
public enum SceneName
{
	Title,
	Stage01,
	Stage02,
	Stage03,
	BaseScene,
}

/// <summary>
/// タグ名を文字列で管理するクラス
/// </summary>
public static class TagName
{
	public const string Untagged = "Untagged";
	public const string Respawn = "Respawn";
	public const string Finish = "Finish";
	public const string EditorOnly = "EditorOnly";
	public const string MainCamera = "MainCamera";
	public const string Player = "Player";
	public const string GameController = "GameController";
	public const string Enemy = "Enemy";
}

/// <summary>
/// レイヤー名を定数で管理するクラス
/// </summary>
public static class LayerName
{
	public const int Default = 0;
	public const int TransparentFX = 1;
	public const int IgnoreRaycast = 2;
	public const int Water = 4;
	public const int UI = 5;
	public const int Ground = 6;
	public const int DefaultMask = 1;
	public const int TransparentFXMask = 2;
	public const int IgnoreRaycastMask = 4;
	public const int WaterMask = 16;
	public const int UIMask = 32;
	public const int GroundMask = 64;
}
}
